title: Module Site
email: your@email.com
description: >- # this means to ignore newlines until "baseurl:"
  Module description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://davegreenwood.github.io/module-blank" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
port: 4000
permalink: pretty

markdown: kramdown

header_pages:
  - about.md
  - lectures.md
